In [1]:
# 주피터노트북 셀 스타일 조절
from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

C:\Users\USER\AppData\Local\Temp\ipykernel_10104\2108606501.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [2]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
# 메소드와 속성
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

# ndim(dimention, rank)

In [5]:
a = np.array(0)

In [6]:
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [7]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [9]:
a = np.array([[2, 4, 6], [1, 3, 5]])
a, a.ndim, type(a)

(array([[2, 4, 6],
        [1, 3, 5]]),
 2,
 numpy.ndarray)

In [11]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

# shape

In [12]:
a.shape

(2, 2, 3)

In [13]:
a = np.array(3)
a, a.shape

(array(3), ())

In [14]:
a = np.array([1, 3, 5, 7, 9])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [16]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [18]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
a, a.shape, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 (1, 3, 3),
 3,
 numpy.ndarray)

# size
요소의 수

In [19]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [20]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

# 넘파이 배열

In [21]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [26]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size} 길이={(len(myArr))}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5 길이=5


In [27]:
mylist2 = [[1, 2, 3], [10, 20, 30], [100, 200, 300]]
mylist2, len(mylist2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [28]:
myArr = np.array(mylist2)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size} 길이={(len(myArr))}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원=2, 구조=(3, 3) 구조타입=<class 'tuple'>, size=9 길이=3


# 넘파이 배열과 리스트와의 차이점

In [30]:
listA = [10, 30, 50]
listB = [1, 2, 3]

print(listA + listB)
print(listA + 2)

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [31]:
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [32]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


In [9]:
arrB = np.array([4, 5, 'data'])
#print(arrA + arrB)
#print(arrA * arrB)
#print(arrA / arrB)
#print(arrA // arrB) # 몫
#print(arrA % arrB) # 나머지

type(arrB)

numpy.ndarray

In [10]:
arrB

array(['4', '5', 'data'], dtype='<U11')

# dtype

In [3]:
import numpy as np

myList_c = ['안녕', 100, 3.14, True, False]
print(myList_c)

['안녕', 100, 3.14, True, False]


In [4]:
myArr_c = np.array(myList_c)
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [6]:
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype)

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


# Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [7]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\USER\AppData\Local\Temp\ipykernel_3280\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\USER\AppData\Local\Temp\ipykernel_3280\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [9]:
np.log(0)

C:\Users\USER\AppData\Local\Temp\ipykernel_3280\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [10]:
np.exp(-np.inf)

0.0

# 기술통계

In [11]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [12]:
np.mean(x) # 평균

4.8076923076923075

In [13]:
np.var(x) # 분산

115.23224852071006

In [14]:
np.std(x) # 표준 편차

10.734628476137871

In [15]:
np.max(x)

23

In [16]:
np.min(x)

-24

In [17]:
np.median(x) # 중앙값

5.0

# 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [18]:
np.percentile(x, 0) # 최소값

-24.0

In [19]:
np.percentile(x, 25) # 1사분위 수

0.0

In [20]:
np.percentile(x, 50) # 2사분위 수

5.0

In [21]:
np.percentile(x, 75) # 3사분위 수

10.0

In [22]:
np.percentile(x, 100) # 최대값

23.0

# 넘파이 함수로 배열 만들기
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소

In [26]:
print(np.ones(10), np.ones(10).dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [27]:
print(np.ones((2, 4)), np.ones((2, 4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [28]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [29]:
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [30]:
print(np.zeros((3, 3)), np.zeros((3, 3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [32]:
# 메모리가 비어있음
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3, 3)), np.empty((3, 3)).dtype)
print(np.empty((3, 3)))
print(np.empty((3, 3), dtype = int)) # 기존 메모리에 있던 값을 출력한다.(정확히 알 수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[    4128860     6029375     3801155]
 [    5570652     6619251     7536754]
 [-1129250816         669           0]]


In [33]:
# 리스트 + 레인지
print(list(range(1, 21)), type(list(range(1, 21))))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [35]:
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20, 2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [39]:
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [40]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5) #시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [42]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [43]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [44]:
arr = arr.reshape(10, 5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [45]:
arr2 = arr.reshape(5, 10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [46]:
# 2차원 -> 1ckdnjs
# 넘파이배열.flatten()

arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [51]:
# 1 ~ 100 사이에 짝수로 된 넘파이 배열 생성
a = np.arange(2, 101, 2)
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [53]:
a.reshape(5, 10)

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [54]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.

arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [59]:
# 4개 칼럼으로 배열 모형을 만들자

a = np.arange(1, 21).reshape(5, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [58]:
a.reshape(-1, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# 사이즈가 맞아야 한다.
# np.arange(1, 21).reshape(-1, 7)

In [60]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [61]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [62]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [63]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [64]:
a.shape = -1, 2
a, a.shape

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 (6, 2))

In [65]:
a.shape = -1, 3
a, a.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [66]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

# 넘파이배열의 자료형 형변환

배열명2 = 배열명1.astype(자료형)

자료형 = np.float64, np.int32

In [67]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [69]:
matrix2 = matrix1.reshape(3, 3)
matrix2, matrix2.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [71]:
matrix = np.arange(1, 10, dtype=float).reshape(3, 3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [72]:
matrix = np.arange(1, 10, dtype='str').reshape(3, 3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

In [73]:
# 정수형 -> 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [74]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [75]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [76]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [77]:
# 문자열 숫자 -> 정수, 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [78]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

# 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파일배열[i][j] : i행 j열

## 1D array

In [80]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [81]:
a[0]

1

In [82]:
a[2]

5

In [83]:
a[4]

9

In [84]:
a[-1]

9

In [85]:
a[-3]

5

In [86]:
a[-5]

1

In [89]:
a[[0, 2, 4]]

array([1, 5, 9])

In [90]:
a

array([1, 3, 5, 7, 9])

In [92]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array([[1, 3], [4, 2]])
b

array([[1, 3],
       [4, 2]])

In [93]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우, 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [95]:
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [96]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [97]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

## 2D array

In [98]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [100]:
# 2차원 인덱싱할 때,값을 하나만 넣으면 행인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [101]:
a[1]

array([5, 6, 7, 8, 9])

In [105]:
a[2]

array([10, 11, 12, 13, 14])

In [106]:
a[-1]

array([10, 11, 12, 13, 14])

In [107]:
a[-2]

array([5, 6, 7, 8, 9])

In [108]:
a[-3]

array([0, 1, 2, 3, 4])

In [109]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [110]:
a[0, 0]

0

In [111]:
a[0, 1]

1

In [112]:
a[0, 2]

2

In [113]:
a[1, 0]

5

In [114]:
a[1, 1]

6

In [115]:
a[1, 2]

7

In [116]:
a[2, 0]

10

In [117]:
a[2, 2]

12

In [118]:
a[-1, 0]

10

In [119]:
a[-1, 1]

11

In [120]:
a[-1, 2]

12

In [140]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [141]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [142]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [143]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [144]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3, 4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [145]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [146]:
# 2차원에서 1번째 행 1번째 열
matrix_b[0, 0]

0

In [148]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
matrix_b[-1, -1]

11

In [150]:
matrix_b[2, 0] = 100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

# 넘파이배열 슬라이싱
1차원
- 넘파이배열[:end]
- 넘파이배열[start:]
- 넘파이배열[start:end]
- 넘파이배열[start:end:step]


2차원
- 넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

## 1D array

In [151]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [152]:
a[:]

array([1, 3, 5, 7, 9])

In [153]:
a[1:]

array([3, 5, 7, 9])

In [154]:
a[-1:]

array([9])

In [155]:
a[:3]

array([1, 3, 5])

In [156]:
a[:-1]

array([1, 3, 5, 7])

In [157]:
a[1:4]

array([3, 5, 7])

In [158]:
a[1:-1]

array([3, 5, 7])

In [159]:
a[-1:1]

array([], dtype=int32)

In [160]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
a[::2]

array([0, 2, 4, 6, 8])

In [162]:
a[::5]

array([0, 5])

In [163]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [164]:
a[1::2]

array([1, 3, 5, 7, 9])

In [165]:
a[:-2:2]

array([0, 2, 4, 6])

# 2D array

In [166]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [167]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [168]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [169]:
a[3:]

array([], shape=(0, 5), dtype=int32)

In [170]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [171]:
a[-3:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [172]:
a[:0]

array([], shape=(0, 5), dtype=int32)

In [173]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [174]:
a[:, 0:1]

array([[10],
       [15],
       [20]])

In [175]:
a[:, 1:-1]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [176]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [178]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
a[1:2, 2:3]

array([[22]])

In [180]:
a[:, :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
a[:, 1:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
a[:, 3:]

array([[13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59],
       [63, 64, 65, 66, 67, 68, 69],
       [73, 74, 75, 76, 77, 78, 79],
       [83, 84, 85, 86, 87, 88, 89],
       [93, 94, 95, 96, 97, 98, 99]])

In [183]:
a[:, -1:]

array([[19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [184]:
a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [187]:
a[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

# 전치행렬

In [188]:
matrix_d = np.arange(1,7).reshape(3, 2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [190]:
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [191]:
print(matrix_d.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


# 난수로 구성된 넘파이 배열
np.random.randint(start, end, n) : 정수 난수

np.random.randint(start, end, (i, j))

In [ ]:
np.random?

In [192]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([9, 2, 8, 8, 5, 9, 3, 9, 3, 8])

In [193]:
# 2행 5열로 출력
np.random.randint(1, 10, (2, 5))

array([[7, 6, 4, 6, 5],
       [9, 6, 9, 2, 1]])

# 섞기
np.random.shuffle(넘파이배열) 원본에 바로 적용

In [194]:
np.random.shuffle

<function RandomState.shuffle>

In [195]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1, 11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [196]:
np.random.shuffle(matrix_e)
matrix_e

array([10,  4,  6,  3,  9,  7,  1,  2,  5,  8])

In [208]:
num = np.arange(1, 46)
lotto = np.random.shuffle(num)
lotto

In [210]:
lotto = np.random.randint(1, 46, 6)
lotto

array([ 4, 29, 34, 40, 26, 28])

# 실수 난수

np.random.randn(n) np.random.randn(i, j)



In [211]:
np.random.randn

<function RandomState.randn>

In [213]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산 1
matrix1

array([ 0.89689417,  2.20030782,  0.16443315,  1.00689992, -1.20217541,
        0.2464724 ,  0.64728539,  0.24303971,  1.49472759,  0.21706112])

In [214]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-0.44134707,  1.00822309, -1.06273817, -0.24374958],
       [-0.57174175,  0.4628562 ,  0.05966913, -1.30079688],
       [-0.64018633,  0.45539074,  0.75654626,  1.41684055],
       [-0.54029661, -0.22891325, -0.19061512, -0.40461078]])

In [216]:
matrix1.max(), matrix1.min()

(2.2003078216662826, -1.2021754060250343)

# 집계함수에서의 축
- 2차원에서의 집계합수(sum, mean)
- axis = 0, 1
- np.sum(넘파이배열, axis=0/1)
- np.mean(넘파이배열, axis=0/1)
- np.sort(넘파이배열, axis=0/1)

In [217]:
m1 = np.random.randint(1, 50, (5, 5))
m1

array([[19, 26, 48, 42, 16],
       [22, 11, 13, 35, 44],
       [44,  4, 42, 49,  4],
       [11,  6, 37, 13, 45],
       [16,  9, 24, 47,  6]])

In [218]:
np.sum(m1, axis=0) # (x)행 합계

array([112,  56, 164, 186, 115])

In [220]:
np.sum(m1[1], axis=0)

125

In [222]:
# 1번째 행의 합계
np.sum(m1[0,:], axis=0)

151

In [223]:
np.sum(m1, axis=1) # 열(y) 합계

array([151, 125, 143, 112, 102])

# np.sort()

In [224]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50, (4, 3))
m2

array([[11, 18, 22],
       [ 8,  5, 42],
       [23, 44, 38],
       [43, 47,  5]])

In [226]:
np.sort(m2)

array([[11, 18, 22],
       [ 5,  8, 42],
       [23, 38, 44],
       [ 5, 43, 47]])

In [228]:
np.sort(m2, axis = 0) # 행방향 오름차순(요소별로)

array([[ 8,  5,  5],
       [11, 18, 22],
       [23, 44, 38],
       [43, 47, 42]])

In [229]:
m2[::-1, ::]

array([[43, 47,  5],
       [23, 44, 38],
       [ 8,  5, 42],
       [11, 18, 22]])

In [230]:
np.sort(m2, axis = 1)

array([[11, 18, 22],
       [ 5,  8, 42],
       [23, 38, 44],
       [ 5, 43, 47]])

# 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [238]:
x = np.array([9, 10, 4])
x

array([ 9, 10,  4])

In [241]:
np.argsort(x) # 오름차순 정렬 4, 9, 10 의 인덱스 값

array([2, 0, 1], dtype=int64)

In [240]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([ 4,  9, 10])

# 넘파이 배열 요소 추가와 삭제

In [2]:
import numpy as np

In [3]:
m3 = np.arange(1, 11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [5]:
m3[-1]

10

In [6]:
np.insert(m3, -1, 500)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [7]:
np.insert(m3, len(m3), 500)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [8]:
m4 = np.arange(1, 10).reshape(3, 3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.insert(m4, 0, 100) # 2차원 배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [10]:
np.insert(m4, 0, 100, axis = 1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [11]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100, 200, 300], axis = 1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [12]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100, 200, 300], axis = 0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [13]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.delete(m4, 0, axis = 0)

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 배열 합치기

np.vstack((배열1,배열2....)) : 세로 합치기

np.hstack((배열1,배열2....)) : 가로 합치기

np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [19]:
c = np.array([[1, 2, 3]])
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [20]:
d = np.array([[4, 5, 6]])
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [21]:
f = np.concatenate((c, d), axis = 0)
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [22]:
f = np.concatenate((c, d), axis = 1)
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

# boolean indexing, mask
조건절의 결과는 True, False로 반환

True인 결과의 데이터 반환

넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [23]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [25]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
(matrix > 10).sum()

10

In [27]:
a = np.random.randint(1, 100, 30)
a

array([59, 42, 48, 24, 78, 22, 69, 76, 66, 18, 33, 46, 95, 92, 11, 18, 71,
       14, 10, 36, 21, 15, 83, 83, 44, 46, 74, 81, 27, 21])

In [38]:
a[(a > 30) & (a < 70)]

array([59, 42, 48, 69, 66, 33, 46, 36, 44, 46])

In [40]:
# ~ 은 reverse 를 의미
a[~(a > 30) & (a < 70)]

array([24, 22, 18, 11, 18, 14, 10, 21, 15, 27, 21])

In [41]:
# 10보다 작거나 90보다 큰 수
a[(a < 10) | (a > 90)]

array([95, 92])

# fancy indexing(filtering)
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]

넘파이배열2 : 인덱스 역할 (only 정수형)

In [42]:
n = np.random.randint(1, 100, 30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([26,  5, 54, 61, 66, 53, 90, 34, 87, 57, 67, 57,  4, 29, 30, 12, 35,
        75, 60, 37, 87, 27, 45, 77, 90, 20, 74, 80, 44, 19]),
 array([26, 54, 61, 67, 87]))

# np.where()를 이용한 필터링
np.where(조건식) : 조건식 만족하는 인덱스 반환

np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값

배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [43]:
np.where?

In [44]:
a = np.arange(10)
a, np.where(a < 5, a, 10 * a)
# a 가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [46]:
b = np.arange(20, 31)
b, np.where(b < 25)
# 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))